/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_api_v1_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Agent Endpoint */
        post: operations["run_agent_endpoint_api_v1_agents__agent_name__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cards */
        get: operations["list_cards_api_v1_cards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_name}/card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent Card */
        get: operations["get_agent_card_api_v1_agents__agent_name__card_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_name}/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grade Agent */
        post: operations["grade_agent_api_v1_agents__agent_name__grade_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tools */
        get: operations["list_tools_api_v1_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Classes */
        get: operations["list_classes_api_v1_classes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_name}/builder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent Builder Detail */
        get: operations["get_agent_builder_detail_api_v1_agents__agent_name__builder_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_name}/sample-input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sample Input */
        get: operations["get_sample_input_api_v1_agents__agent_name__sample_input_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/builder/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Agent Endpoint */
        post: operations["create_agent_endpoint_api_v1_builder_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/builder/agents/{agent_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Agent Endpoint */
        put: operations["update_agent_endpoint_api_v1_builder_agents__agent_name__put"];
        post?: never;
        /** Delete Agent Endpoint */
        delete: operations["delete_agent_endpoint_api_v1_builder_agents__agent_name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/builder/agents/{agent_name}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplicate Agent Endpoint */
        post: operations["duplicate_agent_endpoint_api_v1_builder_agents__agent_name__duplicate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/builder/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Class Endpoint */
        post: operations["create_class_endpoint_api_v1_builder_classes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/builder/model-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Check Endpoint */
        get: operations["model_check_endpoint_api_v1_builder_model_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gm/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gm Queue */
        get: operations["gm_queue_api_v1_gm_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gm/queue/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gm Queue Process */
        post: operations["gm_queue_process_api_v1_gm_queue_process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gm/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gm Suggestions */
        get: operations["gm_suggestions_api_v1_gm_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gm/suggestions/{suggestion_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gm Approve Suggestion
         * @description Apply a GM-suggested system prompt via the normal builder update path,
         *     so it inherits validate-then-commit and hot-reload like any other edit.
         */
        post: operations["gm_approve_suggestion_api_v1_gm_suggestions__suggestion_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gm/suggestions/{suggestion_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gm Reject Suggestion */
        post: operations["gm_reject_suggestion_api_v1_gm_suggestions__suggestion_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_v1_settings_get"];
        /**
         * Put Settings
         * @description Merge the patch over current settings, persist, and apply to the process.
         *
         *     Process-global by nature: flipping stub mode changes behaviour for every
         *     caller of this server, not just this browser tab. That is acceptable for a
         *     playground that binds to localhost with no auth layer, and it is what makes
         *     the setting take effect without a restart.
         */
        put: operations["put_settings_api_v1_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        /** Create Model */
        post: operations["create_model_api_v1_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Model */
        delete: operations["delete_model_api_v1_models__model_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cards Page */
        get: operations["cards_page_cards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/builder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Builder Page */
        get: operations["builder_page_builder_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentBuilderDetail */
        AgentBuilderDetail: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** System Prompt */
            system_prompt: string;
            /** Model */
            model: string;
            /** Temperature */
            temperature: number;
            /** Tools */
            tools: string[];
            /** Feeds */
            feeds: string[];
            /** Card */
            card: {
                [key: string]: unknown;
            } | null;
            /** Is Core */
            is_core: boolean;
            /** Output Model Editable */
            output_model_editable: boolean;
            /** Output Fields Summary */
            output_fields_summary: {
                [key: string]: string;
            };
            /** Sample Input */
            sample_input: {
                [key: string]: unknown;
            } | null;
        };
        /** AgentSummary */
        AgentSummary: {
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /** CardDetail */
        CardDetail: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Main Class */
            main_class: string;
            /** Sub Class */
            sub_class: string | null;
            /** Portrait */
            portrait: string;
            /** Level */
            level: number;
            /** Xp */
            xp: number;
            /** Base Stats */
            base_stats: {
                [key: string]: number;
            };
            /** Class Stats */
            class_stats: {
                [key: string]: number;
            };
            /**
             * Awaiting Respec
             * @default false
             */
            awaiting_respec: boolean;
            /** Backstory */
            backstory: string;
            /** Unlock Table */
            unlock_table: {
                [key: string]: unknown;
            }[];
            /** Tool Proficiency */
            tool_proficiency: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        /** CardSpec */
        CardSpec: {
            /** Main Class */
            main_class: string;
            /** Sub Class */
            sub_class?: string | null;
            /** Title */
            title?: string | null;
            /**
             * Backstory
             * @default
             */
            backstory: string;
            /**
             * Portrait
             * @default
             */
            portrait: string;
            /** Base Stats */
            base_stats?: {
                [key: string]: number;
            } | null;
            /** Unlock Table */
            unlock_table?: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Level
             * @default 1
             */
            level: number;
            /**
             * Xp
             * @default 0
             */
            xp: number;
        };
        /** CardSummary */
        CardSummary: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Main Class */
            main_class: string;
            /** Sub Class */
            sub_class: string | null;
            /** Portrait */
            portrait: string;
            /** Level */
            level: number;
            /** Xp */
            xp: number;
            /** Base Stats */
            base_stats: {
                [key: string]: number;
            };
            /** Class Stats */
            class_stats: {
                [key: string]: number;
            };
            /**
             * Awaiting Respec
             * @default false
             */
            awaiting_respec: boolean;
        };
        /** ClassSummary */
        ClassSummary: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Stats */
            stats: {
                [key: string]: number;
            };
        };
        /** CreateAgentRequest */
        CreateAgentRequest: {
            /** Name */
            name: string;
            /** System Prompt */
            system_prompt: string;
            /** Output Fields */
            output_fields: components["schemas"]["FieldSpec"][];
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Model
             * @default qwen2.5:14b
             */
            model: string;
            /**
             * Temperature
             * @default 0.7
             */
            temperature: number;
            /**
             * Tools
             * @default []
             */
            tools: string[];
            /**
             * Feeds
             * @default []
             */
            feeds: string[];
            card?: components["schemas"]["CardSpec"] | null;
            /** Sample Input */
            sample_input?: {
                [key: string]: unknown;
            } | null;
        };
        /** CreateClassRequest */
        CreateClassRequest: {
            /** Content */
            content: string;
        };
        /** CreateModelRequest */
        CreateModelRequest: {
            /** Model Id */
            model_id: string;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "local" | "frontier";
            /** Base Url */
            base_url?: string | null;
            /** Api Key */
            api_key?: string | null;
        };
        /** DuplicateAgentRequest */
        DuplicateAgentRequest: {
            /** New Name */
            new_name: string;
        };
        /** FieldSpec */
        FieldSpec: {
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "string" | "integer" | "number" | "boolean" | "nested";
            /**
             * Required
             * @default true
             */
            required: boolean;
            /**
             * Is List
             * @default false
             */
            is_list: boolean;
            /**
             * Description
             * @default
             */
            description: string;
            /** Nested Fields */
            nested_fields?: components["schemas"]["FieldSpec"][] | null;
        };
        /** GradeRequest */
        GradeRequest: {
            /** Action */
            action: string;
            /** Tool Used */
            tool_used?: string | null;
        };
        /** GradeResponse */
        GradeResponse: {
            /** Xp Delta */
            xp_delta: number;
            /** New Xp */
            new_xp: number;
            /** New Level */
            new_level: number;
            /** Leveled Up */
            leveled_up: boolean;
            /** Stat Deltas */
            stat_deltas: {
                [key: string]: number;
            };
            /**
             * Events Since Respec
             * @default 0
             */
            events_since_respec: number;
            /**
             * Respec Queued
             * @default false
             */
            respec_queued: boolean;
            /**
             * Respec Processed
             * @default false
             */
            respec_processed: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ModelCheckResponse */
        ModelCheckResponse: {
            /** Available */
            available: boolean;
            /** Message */
            message: string;
        };
        /**
         * ModelProviderEntry
         * @description One registered model: what to call it, and how to reach it.
         *
         *     `kind="local"` entries carry no URL/key of their own — they always resolve
         *     to the shared `provider_url` above, so moving that one URL moves every
         *     local model with it (this mirrors how `provider_url` already worked before
         *     a registry existed: one shared endpoint for every locally-run model).
         *     `kind="frontier"` entries are self-contained: their own base_url and
         *     api_key, since a frontier provider (OpenAI, a hosted gateway, ...) has
         *     nothing to do with the local Ollama instance.
         */
        ModelProviderEntry: {
            /** Model Id */
            model_id: string;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "local" | "frontier";
            /** Base Url */
            base_url?: string | null;
            /** Api Key */
            api_key?: string | null;
        };
        /**
         * ModelProviderSummary
         * @description `ModelProviderEntry` without the api_key — what the browser is allowed to see.
         */
        ModelProviderSummary: {
            /** Model Id */
            model_id: string;
            /** Label */
            label: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "local" | "frontier";
            /** Base Url */
            base_url?: string | null;
            /**
             * Has Api Key
             * @default false
             */
            has_api_key: boolean;
        };
        /**
         * PlaygroundSettings
         * @description Server-side settings the playground UI can edit.
         *
         *     The UI's "Base URL" field is deliberately absent: that is which server the
         *     browser talks to, which only the browser can know. It stays client-side.
         */
        PlaygroundSettings: {
            /**
             * Provider Url
             * @default http://localhost:11434/v1
             */
            provider_url: string;
            /**
             * Default Model
             * @default qwen2.5:14b
             */
            default_model: string;
            /**
             * Gm Model
             * @default qwen2.5:14b
             */
            gm_model: string;
            /**
             * Stub Mode
             * @default false
             */
            stub_mode: boolean;
            /**
             * Respec Threshold
             * @default 12
             */
            respec_threshold: number;
            /**
             * Auto Process Respec
             * @default false
             */
            auto_process_respec: boolean;
            /**
             * Suggestions Enabled
             * @default true
             */
            suggestions_enabled: boolean;
            /**
             * Ntfy Url
             * @default
             */
            ntfy_url: string;
            /**
             * Db Path
             * @default agent_kit.db
             */
            db_path: string;
            /** Models */
            models?: components["schemas"]["ModelProviderEntry"][];
        };
        /** RespecProcessResult */
        RespecProcessResult: {
            /** Processed */
            processed: number;
            /** Resynthesized */
            resynthesized: string[];
            /** Still Pending */
            still_pending: string[];
        };
        /** RespecQueueEntry */
        RespecQueueEntry: {
            /** Agent Name */
            agent_name: string;
            /** Band Signature */
            band_signature: string;
            /** Pending Since */
            pending_since: string | null;
            /** Trait Paragraph */
            trait_paragraph: string;
        };
        /** RunRequest */
        RunRequest: {
            /**
             * Input
             * @description Agent input as a JSON object; passed to Runner as-is
             */
            input: {
                [key: string]: unknown;
            };
        };
        /** RunResponse */
        RunResponse: {
            /** Output */
            output: {
                [key: string]: unknown;
            };
            /** Raw Prompt */
            raw_prompt: string;
            /** Raw Response */
            raw_response: string;
            /**
             * Tools Used
             * @default []
             */
            tools_used: string[];
        };
        /**
         * SettingsUpdate
         * @description Every field optional so the UI can PATCH-style one toggle at a time.
         */
        SettingsUpdate: {
            /** Provider Url */
            provider_url?: string | null;
            /** Default Model */
            default_model?: string | null;
            /** Gm Model */
            gm_model?: string | null;
            /** Stub Mode */
            stub_mode?: boolean | null;
            /** Respec Threshold */
            respec_threshold?: number | null;
            /** Auto Process Respec */
            auto_process_respec?: boolean | null;
            /** Suggestions Enabled */
            suggestions_enabled?: boolean | null;
            /** Ntfy Url */
            ntfy_url?: string | null;
            /** Db Path */
            db_path?: string | null;
        };
        /** SuggestionSummary */
        SuggestionSummary: {
            /** Id */
            id: number;
            /** Agent Name */
            agent_name: string;
            /** Current System Prompt */
            current_system_prompt: string;
            /** Suggested System Prompt */
            suggested_system_prompt: string;
            /** Rationale */
            rationale: string;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
        };
        /** UpdateAgentRequest */
        UpdateAgentRequest: {
            /** System Prompt */
            system_prompt?: string | null;
            /** Output Fields */
            output_fields?: components["schemas"]["FieldSpec"][] | null;
            /** Description */
            description?: string | null;
            /** Model */
            model?: string | null;
            /** Temperature */
            temperature?: number | null;
            /** Tools */
            tools?: string[] | null;
            /** Feeds */
            feeds?: string[] | null;
            card?: components["schemas"]["CardSpec"] | null;
            /** Sample Input */
            sample_input?: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_agents_api_v1_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSummary"][];
                };
            };
        };
    };
    run_agent_endpoint_api_v1_agents__agent_name__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cards_api_v1_cards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardSummary"][];
                };
            };
        };
    };
    get_agent_card_api_v1_agents__agent_name__card_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grade_agent_api_v1_agents__agent_name__grade_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GradeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tools_api_v1_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    list_classes_api_v1_classes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassSummary"][];
                };
            };
        };
    };
    get_agent_builder_detail_api_v1_agents__agent_name__builder_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentBuilderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sample_input_api_v1_agents__agent_name__sample_input_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    } | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_endpoint_api_v1_builder_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentBuilderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_agent_endpoint_api_v1_builder_agents__agent_name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAgentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentBuilderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_agent_endpoint_api_v1_builder_agents__agent_name__delete: {
        parameters: {
            query?: {
                confirm?: boolean;
                confirm_core?: boolean;
            };
            header?: never;
            path: {
                agent_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_agent_endpoint_api_v1_builder_agents__agent_name__duplicate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuplicateAgentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentBuilderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_class_endpoint_api_v1_builder_classes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClassRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_check_endpoint_api_v1_builder_model_check_get: {
        parameters: {
            query: {
                model: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gm_queue_api_v1_gm_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespecQueueEntry"][];
                };
            };
        };
    };
    gm_queue_process_api_v1_gm_queue_process_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespecProcessResult"];
                };
            };
        };
    };
    gm_suggestions_api_v1_gm_suggestions_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gm_approve_suggestion_api_v1_gm_suggestions__suggestion_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gm_reject_suggestion_api_v1_gm_suggestions__suggestion_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaygroundSettings"];
                };
            };
        };
    };
    put_settings_api_v1_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaygroundSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelProviderSummary"][];
                };
            };
        };
    };
    create_model_api_v1_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateModelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelProviderSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_model_api_v1_models__model_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    cards_page_cards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    builder_page_builder_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
}
