"""model_codegen — turns a builder field-spec into real, importable Pydantic model source.

Pure functions, no file I/O. `loader.py` resolves `output_model:` via
`importlib.import_module` + `getattr`, which requires a real module attribute —
so generated models are rendered as Python source and written to a real .py
file by the caller (agent_kit/builder.py), not constructed in memory.
"""

from __future__ import annotations

import re
from typing import Literal

from pydantic import BaseModel

from agent_kit.errors import (
    DuplicateFieldNameError,
    EmptyOutputModelError,
    InvalidFieldSpecError,
    NestingDepthExceededError,
    ReservedFieldNameError,
)

FieldType = Literal["string", "integer", "number", "boolean", "nested"]

_MAX_NESTING_DEPTH = 1
_RESERVED_EXACT_NAMES = {"model_config", "model_fields", "model_computed_fields"}
_TYPE_MAP = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
}


class FieldSpec(BaseModel):
    name: str
    type: FieldType
    required: bool = True
    is_list: bool = False
    description: str = ""
    nested_fields: list["FieldSpec"] | None = None


FieldSpec.model_rebuild()


def _is_valid_identifier(name: str) -> bool:
    return name.isidentifier() and not name.startswith("_")


def validate_field_specs(fields: list[FieldSpec], _depth: int = 0) -> None:
    if not fields:
        raise EmptyOutputModelError("output model must have at least one field")

    seen_names: set[str] = set()
    for f in fields:
        if not _is_valid_identifier(f.name):
            raise InvalidFieldSpecError(f"'{f.name}' is not a valid Python field name")
        if f.name.startswith("model_") or f.name in _RESERVED_EXACT_NAMES:
            raise ReservedFieldNameError(
                f"'{f.name}' collides with a reserved BaseModel attribute name"
            )
        if f.name in seen_names:
            raise DuplicateFieldNameError(f"duplicate field name '{f.name}' at the same level")
        seen_names.add(f.name)

        if f.type == "nested":
            if not f.nested_fields:
                raise InvalidFieldSpecError(
                    f"field '{f.name}' has type 'nested' but no nested_fields"
                )
            if _depth >= _MAX_NESTING_DEPTH:
                raise NestingDepthExceededError(
                    f"field '{f.name}' exceeds the maximum nesting depth of {_MAX_NESTING_DEPTH}"
                )
            validate_field_specs(f.nested_fields, _depth=_depth + 1)
        elif f.nested_fields:
            raise InvalidFieldSpecError(
                f"field '{f.name}' has nested_fields but type is '{f.type}', not 'nested'"
            )


def to_pascal_case(name: str) -> str:
    parts = re.split(r"[^a-zA-Z0-9]+", name)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def output_class_name(agent_name: str) -> str:
    return f"{to_pascal_case(agent_name)}Output"


def _python_type(field: FieldSpec, root_class_name: str) -> str:
    if field.type == "nested":
        base = f"{root_class_name}{to_pascal_case(field.name)}"
    else:
        base = _TYPE_MAP[field.type]
    if field.is_list:
        base = f"list[{base}]"
    if not field.required:
        base = f"{base} | None"
    return base


def _render_class_body(fields: list[FieldSpec], root_class_name: str) -> list[str]:
    lines = []
    for f in fields:
        field_type = _python_type(f, root_class_name)
        default = "" if f.required else " = None"
        lines.append(f"    {f.name}: {field_type}{default}")
    return lines


def generate_model_source(agent_name: str, fields: list[FieldSpec]) -> str:
    validate_field_specs(fields)
    root_name = output_class_name(agent_name)

    nested_class_blocks: list[str] = []
    for f in fields:
        if f.type == "nested":
            nested_class_name = f"{root_name}{to_pascal_case(f.name)}"
            block = [f"class {nested_class_name}(BaseModel):"]
            block.extend(_render_class_body(f.nested_fields, nested_class_name))
            nested_class_blocks.append("\n".join(block))

    root_block = [f"class {root_name}(BaseModel):"]
    root_block.extend(_render_class_body(fields, root_name))

    header = (
        '"""Generated by agent-kit Agent Builder — do not edit by hand."""\n\n'
        "from __future__ import annotations\n\n"
        "from pydantic import BaseModel\n"
    )

    blocks = nested_class_blocks + ["\n".join(root_block)]
    return header + "\n\n\n" + "\n\n\n".join(blocks) + "\n"
